//	DeviceIoControl IOCTL codes supported by UsbKbd

#define IOCTL_USBKBD_SET_READ_TIMEOUT CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x801,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_USBKBD_GET_DEVICE_DESCRIPTOR CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x802,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_USBKBD_GET_CONFIGURATION_DESCRIPTORS CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x803,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_USBKBD_GET_SPECIFIED_DESCRIPTOR CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x804,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_USBKBD_GET_STATUSES CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x805,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_USBKBD_GET_FRAME_INFO CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x806,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)



