//	DeviceIoControl IOCTL codes supported by Wdm1

#define IOCTL_WDM1_ZERO_BUFFER CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x801,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_WDM1_REMOVE_BUFFER CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x802,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_WDM1_GET_BUFFER_SIZE CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x803,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_WDM1_GET_BUFFER CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x804,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_WDM1_UNRECOGNISED CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x805,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_WDM1_GET_BUILDTIME CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x806,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)

#define IOCTL_WDM1_RPN_PUSH CTL_CODE(	 	\
			FILE_DEVICE_UNKNOWN,			\
			0x807,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_POP CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x808,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_ADD CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x809,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_SUB CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x810,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_MULT CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x811,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_DIV CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x812,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_GETDIVREST CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x813,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)
			
#define IOCTL_WDM1_RPN_DUPLI CTL_CODE(	\
			FILE_DEVICE_UNKNOWN,			\
			0x814,							\
			METHOD_BUFFERED,				\
			FILE_ANY_ACCESS)